### PR TITLE
Allow specifying doctype in registry

### PR DESCRIPTION
**Pull request by pfitzseb**
With this PR package authors can specify how and where their docs are in https://github.com/JuliaDocs/DocumentationGeneratorRegistry.

### CODE REVIEW

**Comment by mortenpi** [comment]
> I'd expect the docs links to be pretty stable in general though (you probably won't move to a different repo that often, and if you self-host the docs you can just use `.../latest`).

In my experience, at least the URL changes are not that uncommon. [Documenter's Examples page](https://juliadocs.github.io/Documenter.jl/stable/man/examples/#Registered-1) needs to be updated every few months because a URL has become out of date (org. names, owners changing, moving to and from the github.io domain etc). And it's just a subset of packages.

**Comment by StefanKarpinski** [comment]
A couple of reactions: Do we need the `metadata` prefix? Could this be a top-level `[docs]` section The keys seems a bit ad hoc—do we need all of them? They seem to be mutually exclusive, right? Then perhaps it would be better to make the format be something like this:
```toml
[docs]
method = "git repo"
location = "https://github.com/JunoLab/JunoDocs.jl"
```
```toml
[docs]
method = "hosted"
location = "https://docs.junolab.org"
```
```toml
[docs]
method = "vendored"
location = "dir"
```
This feels less ad hoc and a bit more structured to me. Mostly because it feels better to me when then TOML values take on a range of options rather than the keys.

**Comment by pfitzseb** [comment]
That does seem considerably cleaner, yes. 
The only advantage for having multiple keys would be that a package author could multiple options and we fall back to another one if the one with the highest priority doesn't work. Could be handled by an array of such objects though.

**Comment by fredrikekre** [comment]
The idea with `[metadata]` was to do something like https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table-optional, i.e. make `[metadata]` a Pkg-blessed entry, which will be ignored by the package manager. Then external tools (like DocumentationGenerator) can tell people to include stuff there instead of adding stuff to the top-level of the project file.

**Comment by StefanKarpinski** [comment]
> @pfitzseb: Could be handled by an array of such objects though.

Right. One could allow the top-level `docs` to be a dict with a single `method`/`location` map or an array of such maps, i.e.
```toml
[[docs]]
method = "git repo"
location = "https://github.com/JunoLab/JunoDocs.jl"

[[docs]]
method = "hosted"
location = "https://docs.junolab.org"

[[docs]]
method = "vendored"
location = "dir"
```

> @fredrikekre: The idea with [metadata] was...

Then do we want something like
```toml
[metadata.DocumentGenerator]
method = "git-repo"
location = "https://github.com/JunoLab/JunoDocs.jl"
```
I.e. should the key in `metadata` be the package name?

**Comment by fredrikekre** [comment]
> Then do we want something like

Yea maybe. The alternative is of course to have a `.documentationgenerator.toml` file but maybe its nice to piggyback on `Project.toml`...

**Comment by pfitzseb** [comment]
> The alternative is of course to have a .documentationgenerator.toml file but maybe its nice to piggyback on Project.toml...

Or in Metadata.toml?

I do feel like there's some merit to having everything in one file though.

**Comment by StefanKarpinski** [comment]
> I do feel like there's some merit to having everything in one file though.

The best thing about one file (or two actually, since Manifest.toml) is that it's easier to share with people and see what's going on. Does this kind of metadata need to be shared often? Is it something that one should see when looking at the normal project info?

Another thing to keep in mind is that the name `DocumentationGenerator` really only has meaning where that's a `[deps]` or `[extras]` entry. That's not the case in the top-level project file usually, right? But it would be the case in a `doc/Project.toml` file. Perhaps that's where this info should go?

**Comment by pfitzseb** [comment]
> The best thing about one file (or two actually, since Manifest.toml) is that it's easier to share with people and see what's going on. Does this kind of metadata need to be shared often? Is it something that one should see when looking at the normal project info?

When looking at normal project info? Probably not. It's also not really related to Pkg operations at all.

So what do people think about introducing a `Metadata.toml` where each metadata consumer can have it's own top-level key? That seems like a sane resolution to https://github.com/JuliaLang/Pkg.jl/issues/1070, and I think I'd prefer that over separate tomls for each of those top-level keys.

**Comment by StefanKarpinski** [comment]
Question: is metadata distinct from configuration?

**Comment by StefanKarpinski** [comment]
Ok, it's configuration if there's an application that's being configured and this info is being used to configure the `DocumentationGenerator` package. If that's not the case, then it's data. Just to make progress on this, let me try to synthesize some of the ideas here so far into a proposal. If we put this in a separate `Metadata.toml` file, it would look like this if there's one external hosting method/location:
```toml
# Metadata.toml
[DocumentationGenerator]
method = "hosted"
location = "https://docs.julialang.org"
```
If there's more than one external hosting method/location, then it would look like this:
```toml
# Metadata.toml
[[DocumentationGenerator]]
method = "git-repo"
location = "https://github.com/JunoLab/JunoDocs.jl"

[[DocumentationGenerator]]
method = "hosted"
location = "https://docs.junolab.org"

[[DocumentationGenerator]]
method = "vendored"
location = "dir"
```
Do we need another layer of nesting in there for other kinds of configuration that `DocumentationGenerator` might need? If we put it into `Project.toml` then it's basically the same format except nested under a `[metadata]` section. I'm inclined to go with the `Metadata.toml` file because of the fairly deep nesting.

**Comment by pfitzseb** [comment]
Alright, I implemented the `Metadata.toml` parsing now ([example here](https://github.com/JunoLab/Juno.jl/blob/master/Metadata.toml)).

Imho this should be fine as is, but it is possible that there are additional configuration options we might want to add under the `DocumentationGenerator` key, in which case the array syntax doesn't really work anymore.

**Comment by StefanKarpinski** [comment]
How necessary is having multiple methods of hosting docs?

**Comment by pfitzseb** [comment]
Heh, good point. Probably not very necessary at all.

**Comment by fredrikekre** [comment]
What is the motivation for this configuration to be in the repo again? Would it not be simpler with an external database(https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/36#issuecomment-490472898)? If you move the docs or w/e you just update that database instead of having to modify your repo and make a new tag etc.

**Comment by StefanKarpinski** [comment]
This does seems like kind of an oddball thing to have in the project repo.

**Comment by pfitzseb** [comment]
Alright, the registry is working quite nicely now and has CI that checks PRs for validity as well as an interactive script that allows you to easily add new entries. Would be cool if someone could give that a go, and then we can merge this I think.

**Comment by fredrikekre** [comment]
Nice, maybe update the PR title to reflect the new implementation?

**Pull request merged**
